config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :biotipos
  resources :planos
  resources :usuarios
  resources :logado

  get 'welcome/index'
  get 'login/index'

  root to: 'welcome#index'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/biotipo.rb
class Biotipo < ApplicationRecord
end

app/models/plano.rb
class Plano < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/usuario.rb
class Usuario < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/biotipos_controller.rb
class BiotiposController < ApplicationController
  before_action :set_biotipo, only: %i[ show edit update destroy ]

  # GET /biotipos or /biotipos.json
  def index
    @biotipos = Biotipo.all
  end

  # GET /biotipos/1 or /biotipos/1.json
  def show
  end

  # GET /biotipos/new
  def new
    @biotipo = Biotipo.new
  end

  # GET /biotipos/1/edit
  def edit
  end

  # POST /biotipos or /biotipos.json
  def create
    @biotipo = Biotipo.new(biotipo_params)

    respond_to do |format|
      if @biotipo.save
        format.html { redirect_to biotipo_url(@biotipo), notice: "Biotipo was successfully created." }
        format.json { render :show, status: :created, location: @biotipo }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @biotipo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /biotipos/1 or /biotipos/1.json
  def update
    respond_to do |format|
      if @biotipo.update(biotipo_params)
        format.html { redirect_to biotipo_url(@biotipo), notice: "Biotipo was successfully updated." }
        format.json { render :show, status: :ok, location: @biotipo }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @biotipo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /biotipos/1 or /biotipos/1.json
  def destroy
    @biotipo.destroy

    respond_to do |format|
      format.html { redirect_to biotipos_url, notice: "Biotipo was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_biotipo
      @biotipo = Biotipo.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def biotipo_params
      params.require(:biotipo).permit(:biotipo)
    end
end

app/controllers/logado_controller.rb
class LogadoController < ApplicationController
end
  

app/controllers/login_controller.rb
class LoginController < ApplicationController
end
  

app/controllers/planos_controller.rb
class PlanosController < ApplicationController
  before_action :set_plano, only: %i[ show edit update destroy ]

  # GET /planos or /planos.json
  def index
    @planos = Plano.all
  end

  # GET /planos/1 or /planos/1.json
  def show
  end

  # GET /planos/new
  def new
    @plano = Plano.new
  end

  # GET /planos/1/edit
  def edit
  end

  # POST /planos or /planos.json
  def create
    @plano = Plano.new(plano_params)

    respond_to do |format|
      if @plano.save
        format.html { redirect_to plano_url(@plano), notice: "Plano was successfully created." }
        format.json { render :show, status: :created, location: @plano }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @plano.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /planos/1 or /planos/1.json
  def update
    respond_to do |format|
      if @plano.update(plano_params)
        format.html { redirect_to plano_url(@plano), notice: "Plano was successfully updated." }
        format.json { render :show, status: :ok, location: @plano }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @plano.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /planos/1 or /planos/1.json
  def destroy
    @plano.destroy

    respond_to do |format|
      format.html { redirect_to planos_url, notice: "Plano was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_plano
      @plano = Plano.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def plano_params
      params.require(:plano).permit(:plano)
    end
end

app/controllers/usuarios_controller.rb
class UsuariosController < ApplicationController
  before_action :set_usuario, only: %i[ show edit update destroy ]

  # GET /usuarios or /usuarios.json
  def index
    @usuarios = Usuario.all
  end

  # GET /usuarios/1 or /usuarios/1.json
  def show
  end

  # GET /usuarios/new
  def new
    @usuario = Usuario.new
  end

  # GET /usuarios/1/edit
  def edit
  end

  # POST /usuarios or /usuarios.json
  def create
    @usuario = Usuario.new(usuario_params)

    respond_to do |format|
      if @usuario.save
        format.html { redirect_to usuario_url(@usuario), notice: "Usuario was successfully created." }
        format.json { render :show, status: :created, location: @usuario }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @usuario.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /usuarios/1 or /usuarios/1.json
  def update
    respond_to do |format|
      if @usuario.update(usuario_params)
        format.html { redirect_to usuario_url(@usuario), notice: "Usuario was successfully updated." }
        format.json { render :show, status: :ok, location: @usuario }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @usuario.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /usuarios/1 or /usuarios/1.json
  def destroy
    @usuario.destroy

    respond_to do |format|
      format.html { redirect_to usuarios_url, notice: "Usuario was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_usuario
      @usuario = Usuario.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def usuario_params
      params.require(:usuario).permit(:email, :nome, :telefone, :senha)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
end
  

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/biotipos_helper.rb
module BiotiposHelper
end

app/helpers/planos_helper.rb
module PlanosHelper
end

app/helpers/usuarios_helper.rb
module UsuariosHelper
end

app/views/biotipos/_biotipo.html.erb
<div id="<%= dom_id biotipo %>">
  <p>
    <strong>Biotipo:</strong>
    <%= biotipo.biotipo %>
  </p>

</div>

app/views/biotipos/_form.html.erb
<%= form_with(model: biotipo) do |form| %>
  <% if biotipo.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(biotipo.errors.count, "error") %> prohibited this biotipo from being saved:</h2>

      <ul>
        <% biotipo.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :biotipo, style: "display: block" %>
    <%= form.text_field :biotipo %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/biotipos/edit.html.erb
<h1>Editing biotipo</h1>

<%= render "form", biotipo: @biotipo %>

<br>

<div>
  <%= link_to "Show this biotipo", @biotipo %> |
  <%= link_to "Back to biotipos", biotipos_path %>
</div>

app/views/biotipos/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Biotipos</h1>

<div id="biotipos">
  <% @biotipos.each do |biotipo| %>
    <%= render biotipo %>
    <p>
      <%= link_to "Show this biotipo", biotipo %>
    </p>
  <% end %>
</div>

<%= link_to "New biotipo", new_biotipo_path %>

app/views/biotipos/new.html.erb
<h1>New biotipo</h1>

<%= render "form", biotipo: @biotipo %>

<br>

<div>
  <%= link_to "Back to biotipos", biotipos_path %>
</div>

app/views/biotipos/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @biotipo %>

<div>
  <%= link_to "Edit this biotipo", edit_biotipo_path(@biotipo) %> |
  <%= link_to "Back to biotipos", biotipos_path %>

  <%= button_to "Destroy this biotipo", @biotipo, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Gym</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "scaffold", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <!-- Só uma imagem -->
<nav class="navbar navbar-light">
  <a class="navbar-brand" href="#">
    <%= image_tag('logo_file',width:"60", height:"60" ) %>
  </a>
  <ul class="nav justify-content-end">
        <li class="nav-item">
          <%= link_to 'Home',welcome_index_path , class:'nav-link active' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Login',login_index_path , class:'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Cadastrar-se',new_usuario_path	 , class:'nav-link' %>
        </li>
    </ul>
</nav>
    <%= yield %>
  </body>

  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

</html>

app/views/layouts/user.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/logado/index.html.erb
<h1>TESTE</h1>

app/views/login/index.html.erb
<%= stylesheet_link_tag "login", "data-turbo-track": "reload" %>
<div class="container">
  <h2>Seja Bem-Vindo novamente!</h2>
  <%= form_with(model: Usuario) do |form| %>
  <div class="form-group">
    <%= form.label :email, "Digite seu E-mail:", for:"exampleInputEmail1" %>
    <%= form.email_field :address, class:"form-control", id:"exampleInputEmail1", placeholder:"Seu email" %>
  </div>
  <div class="form-group">
    <%= form.label :password, "Digite sua Senha:", for:"exampleInputPassword1" %>
    <%= form.password_field :password, class:"form-control", id:"exampleInputPassword1", placeholder:"Senha" %>
  </div>
  <div class="form-group">
    <%= form.submit "Logar", class:"btn btn-primary"%>
    <%= link_to 'Back to usuarios',welcome_index_path , class:"btn btn-primary" %>
  </div>
<% end %>
</div>

app/views/planos/_form.html.erb
<%= form_with(model: plano) do |form| %>
  <% if plano.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(plano.errors.count, "error") %> prohibited this plano from being saved:</h2>

      <ul>
        <% plano.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :plano, style: "display: block" %>
    <%= form.text_field :plano %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/planos/_plano.html.erb
<div id="<%= dom_id plano %>">
  <p>
    <strong>Plano:</strong>
    <%= plano.plano %>
  </p>

</div>

app/views/planos/edit.html.erb
<h1>Editing plano</h1>

<%= render "form", plano: @plano %>

<br>

<div>
  <%= link_to "Show this plano", @plano %> |
  <%= link_to "Back to planos", planos_path %>
</div>

app/views/planos/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Planos</h1>

<div id="planos">
  <% @planos.each do |plano| %>
    <%= render plano %>
    <p>
      <%= link_to "Show this plano", plano %>
    </p>
  <% end %>
</div>

<%= link_to "New plano", new_plano_path %>

app/views/planos/new.html.erb
<h1>New plano</h1>

<%= render "form", plano: @plano %>

<br>

<div>
  <%= link_to "Back to planos", planos_path %>
</div>

app/views/planos/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @plano %>

<div>
  <%= link_to "Edit this plano", edit_plano_path(@plano) %> |
  <%= link_to "Back to planos", planos_path %>

  <%= button_to "Destroy this plano", @plano, method: :delete %>
</div>

app/views/usuarios/_form.html.erb
<%= form_with(model: usuario) do |form| %>
  <% if usuario.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(usuario.errors.count, "error") %> prohibited this usuario from being saved:</h2>

      <ul>
        <% usuario.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

<div class="container">
  <h2>Cadastre-se</h2>
    <form>
      <div class="form-group">
        <%= form.label :email, style: "display: block" %>
        <%= form.text_field :email, class:"form-control" ,id:"exampleInputEmail1", placeholder:"Seu email" %>
      </div>
      <div class="form-group">
        <%= form.label :nome, style: "display: block" %>
        <%= form.text_field :nome, class:"form-control" ,id:"exampleInputEmail1", placeholder:"Seu Nome" %>
      </div>
      <div class="form-group">
        <%= form.label :telefone, style: "display: block" %>
        <%= form.number_field :telefone, class:"form-control" ,id:"exampleInputEmail1", placeholder:"Seu email" %>
      </div>
      <div class="form-group">
        <%= form.label :senha, style: "display: block" %>
        <%= form.text_field :senha, class:"form-control" ,id:"exampleInputEmail1", placeholder:"Seu email" %>
      </div>
      <div class="form-group">
        <%= form.submit class:"btn btn-primary"%>
        <%= link_to 'Back to usuarios',welcome_index_path , class:"btn btn-primary" %>
      </div>
    </form>
</div>
<% end %>

app/views/usuarios/_usuario.html.erb
<div id="<%= dom_id usuario %>">
  <p>
    <strong>Email:</strong>
    <%= usuario.email %>
  </p>

  <p>
    <strong>Nome:</strong>
    <%= usuario.nome %>
  </p>

  <p>
    <strong>Telefone:</strong>
    <%= usuario.telefone %>
  </p>

  <p>
    <strong>Senha:</strong>
    <%= usuario.senha %>
  </p>

</div>

app/views/usuarios/edit.html.erb
<h1>Editing usuario</h1>

<%= render "form", usuario: @usuario %>

<br>

<div>
  <%= link_to "Show this usuario", @usuario %> |
  <%= link_to "Back to usuarios", usuarios_path %>
</div>

app/views/usuarios/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Usuarios</h1>

<div id="usuarios">
  <% @usuarios.each do |usuario| %>
    <%= render usuario %>
    <p>
      <%= link_to "Show this usuario", usuario %>
    </p>
  <% end %>
</div>

<%= link_to "New usuario", new_usuario_path %>

app/views/usuarios/new.html.erb
<%= stylesheet_link_tag "login", "data-turbo-track": "reload" %>
<h1>New usuario</h1>

<%= render "form", usuario: @usuario %>

<br>

app/views/usuarios/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @usuario %>

<div>
  <%= link_to "Edit this usuario", edit_usuario_path(@usuario) %> |
  <%= link_to "Back to usuarios", usuarios_path %>

  <%= button_to "Destroy this usuario", @usuario, method: :delete %>
</div>

app/views/welcome/index.html.erb
<%= stylesheet_link_tag "welcome", "data-turbo-track": "reload" %>
<div class="container">
    <div class="welcome-gym">
      <h1>Bem-vindo à Academia <span class="title-bodyfitness">BODYFITNESS</span> </h1>
      <p>O seu destino para alcançar um estilo de vida mais saudável e ativo. Nossa missão é inspirar e capacitar você a atingir seus objetivos de condicionamento físico e bem-estar. Descubra nossa variedade de programas e serviços personalizados, liderados por instrutores apaixonados, e comece sua jornada de transformação hoje mesmo!
  </p>
    </div>
      
  <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
    <ol class="carousel-indicators">
      <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
      <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
      <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner">
      <div class="carousel-item active">
        <%= image_tag('homem-forte-treinando-na-academia', class:"d-block w-100") %>
      </div>
      <div class="carousel-item">
        <%= image_tag('homem-jovem-em-sportswear-um-classe-exercicio-em-um-ginasio.', class:"d-block w-100") %>
      </div>
      <div class="carousel-item">
        <%= image_tag('risen-wang-20jX9b35r_M-unsplash', class:"d-block w-100") %>
      </div>
    </div>
    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">Anterior</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Próximo</span>
    </a>
  </div>
  <div class="about-gym">
    <h1><span class="title-bodyfitness">Sobre a Academia:</span></h1>
    <p>Fundada em BodyFitness, a Academia BodyFitness é o resultado de anos de dedicação ao fitness e à saúde. Nossa equipe de profissionais qualificados está comprometida em ajudar você a se tornar a melhor versão de si mesmo. Com valores fundamentais de dedicação, compromisso e excelência, estamos aqui para apoiar sua jornada de fitness.
    </p>
    <div class="img-draw">
      <%= image_tag('Gym-bro', class:"d-block w-100", margin:"Auto") %>
    </div>
  </div>

  <div class="about-plans">
    <h1><span class="title-bodyfitness">Planos:</span></h1>
    <p>Temos planos de adesão flexíveis para atender às suas necessidades de condicionamento físico. Escolha entre planos mensais, trimestrais ou anuais e aproveite nossa oferta de avaliação gratuita por 1 dia. Nossos preços acessíveis e descontos sazonais garantem que você tenha acesso a programas de qualidade sem quebrar o banco. Entre em contato conosco para obter mais informações.
    </p>

  <div class="card-main">
    <div class="card" style="width: 18rem;">
          <%= image_tag('craig-lovelidge-yDGsn39fbD4-unsplash', class:"card-img-top") %>
          <div class="card-body">
            <h5 class="card-title">Basic</h5>
            <p class="card-text">O Plano Básico é perfeito para quem está começando sua jornada de condicionamento físico ou procura uma opção de baixo custo para manter um estilo de vida ativo.</p>
          </div>
          <div class="btn-plans-card">
            <a href="#" class="btn btn-dark">Adquira o Plano Basic</a>
          </div>
    </div>
    <div class="card" style="width: 18rem;">
          <%= image_tag('michael-starkie-F412aTVczu0-unsplash', class:"card-img-top") %>
          <div class="card-body">
            <h5 class="card-title">Medium</h5>
            <p class="card-text">O Plano Médio é ideal para aqueles que desejam um equilíbrio entre variedade de serviços e acessibilidade.</p>
          </div>
          <div class="btn-plans-card">
            <a href="#" class="btn btn-dark">Adquira o Plano Medium</a>
          </div>
    </div>
    <div class="card" style="width: 18rem;">
          <%= image_tag('b-mat-an-gelo-ZU23GWLoCWc-unsplash', class:"card-img-top") %>
          <div class="card-body">
            <h5 class="card-title">Ultra</h5>
            <p class="card-text">O Plano Ultra é a escolha premium para aqueles que buscam o máximo em resultados e atendimento personalizado.</p>
          </div>
          <div class="btn-plans-card">
            <a href="#" class="btn btn-dark">Adquira o Plano Ultra</a>
          </div>
    </div>
  </div>

    <div class="instrutores">
      <div class="about-personal">
        <h1><span class="title-bodyfitness">Nossos Instrutores Especializados:</span></h1>
        <p>Na Acade mia BODYFITNESS, estamos orgulhosos de contar com uma equipe de instrutores altamente qualificados e dedicados, prontos para guiá-lo em sua jornada de condicionamento físico. Nossos instrutores são mais do que apenas profissionais de fitness; eles são mentores apaixonados que estão comprometidos com o seu sucesso. Conheça alguns dos membros da nossa equipe:</p>
      </div>

      <div class="personal-context">
        <div class="img-personal">
          <%= image_tag('instrutores/rohit-reddy-FGP9ifRTQaI-unsplash') %>
        </div>
        <div class="about-personal">
          <h3><span class="title-bodyfitness">John Anderson</span></h3>
          <p>John Anderson é um instrutor de musculação dedicado e um especialista em treinamento de força. Com uma abordagem baseada em ciência, ele trabalha com seus alunos para alcançar ganhos de força e massa muscular de forma segura e eficaz. John acredita que o desenvolvimento físico é uma jornada que exige compromisso, consistência e uma sólida base de conhecimento. Ele está aqui para orientar você em direção aos seus objetivos de condicionamento físico..</p>
        </div>
      </div>

      <div class="personal-context">
        <div class="img-personal personal-right">
          <%= image_tag('instrutores/julia-rekamie-Z72YujnOrlY-unsplash') %>
        </div>
        <div class="about-personal personal-right">
          <h3><span class="title-bodyfitness">Júlia Rekamie</span></h3>
          <p>Júlia Rekamie é uma instrutora apaixonada por fitness e bem-estar. Com mais de 10 anos de experiência, ela se especializa em aulas de ioga e pilates, ajudando os alunos a encontrar equilíbrio, flexibilidade e paz interior. Sarah acredita que a jornada de condicionamento físico é uma busca holística que engloba mente, corpo e espírito. Ela está comprometida em guiar seus alunos em direção à harmonia e ao bem-estar.</p>
        </div>
      </div>

      <div class="personal-context">
        <div class="img-personal">
          <%= image_tag('instrutores/spencer-davis-0ShTs8iPY28-unsplash') %>
        </div>
        <div class="about-personal">
          <h3> <span class="title-bodyfitness">Emily Reynolds</span></h3>
          <p>Emily Reynolds é uma instrutora de treinamento funcional altamente energética. Com uma paixão pela resistência e pelo condicionamento, ela é conhecida por suas aulas desafiadoras que ajudam os alunos a superar seus limites. Emily acredita que o condicionamento físico é uma jornada pessoal de superação e crescimento, e ela está aqui para motivar e inspirar você em cada passo do caminho.</p>
        </div>
      </div>

    </div>
  </div>

</div>

<footer class="bg-dark text-center text-white">
  <!-- Grid container -->
  <div class="container p-4 pb-0">
    <!-- Section: Social media -->
    <section class="mb-4">
      <!-- Facebook -->
      <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"
        ><i class="fab fa-facebook-f"></i
      ></a>

      <!-- Twitter -->
      <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"
        ><i class="fab fa-twitter"></i
      ></a>

      <!-- Google -->
      <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"
        ><i class="fab fa-google"></i
      ></a>

      <!-- Instagram -->
      <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"
        ><i class="fab fa-instagram"></i
      ></a>

      <!-- Linkedin -->
      <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"
        ><i class="fab fa-linkedin-in"></i
      ></a>

      <!-- Github -->
      <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"
        ><i class="fab fa-github"></i
      ></a>
    </section>
    <!-- Section: Social media -->
  </div>
  <!-- Grid container -->

  <!-- Copyright -->
  <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
    © 2020 Copyright:
    <a class="text-white" href="https://mdbootstrap.com/">MDBootstrap.com</a>
  </div>
  <!-- Copyright -->
</footer>